---
matrixConfig:
  github_error:
    kind: gif
    systems:
      - github
    severity:
      - failed
    image: sunset.gif
    duration: 5
  gitlab_error:
    kind: gif
    systems:
      - gitlab
    severity:
      - failed
    image: car.gif
    duration: 5
  git_success:
    kind: gif
    systems:
      - gitlab
      - github
    severity:
      - success
    image: nyan.gif
    duration: 5
  logoGeneric:
    kind: image
    systems:
      - all
    severity:
      - info
      - success
    image: sthings.png
    duration: 5
  scale_text:
    kind: static
    systems:
      - scale
    severity:
      - info
    text: |
      {{ Message | replace('WEIGHT: ','') }}g
    speed: 5
    font: myfont.bdf
