---
matrixConfig:
  github_error:
    kind: gif
    systems:
      - github
    severity:
      - WARNING
      - ERROR
    image: sunset.gif
    duration: 5
  gitlab_error:
    kind: gif
    systems:
      - gitlab
    severity:
      - WARNING
      - ERROR
    image: car.gif
    duration: 5
  git_success:
    kind: gif
    systems:
      - gitlab
      - github
    severity:
      - SUCCESS
    image: nyan.gif
    duration: 5
  ansible_success:
    kind: image
    systems:
      - ansible
    severity:
      - INFO
      - SUCCESS
    image: sthings.png
    duration: 5
  ansible_error:
    kind: gif
    systems:
      - ansible
    severity:
      - ERROR
    image: 49c6d8004be45c83ce4b4f94278aa28f.gif
    duration: 5
  scale_text:
    kind: static
    systems:
      - scale
    severity:
      - WARNING
      - INFO
    text: |
      {{ message | replace('WEIGHT: ','') }}g
    speed: 5
    font: myfont.bdf

